name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        # Alpha Release
        uses: cla-assistant/github-action@refactor
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REMOTE_REPOSITORY_TOKEN : ${{ secrets.REMOTE_REPOSITORY_TOKEN }}
        with: 
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-cla-document: 'https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md'
          # branch should not be protected
          branch: 'master'
          allowlist: user1,bot*
          empty-commit-flag: false
          remote-repository-name: safebees
          remote-organization-name: ibakshay  
          #optional
        #  signed-commit-message: 'chore(cla): $contributorName has signed the CLA in #$pullRequestNo'
         # custom-notsigned-prcomment: 'Introductory message to ask new contributors to sign'
         # create-file-commit-message: 'Commit message when a new file is created'
          #custom-allsigned-prcomment: 'Commit message when everyone has signed, defaults to **CLA Assistant Lite** All Contributors have signed the CLA.'
