name: "deno test"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
    
jobs:
  denotest:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
        with:
         deno-version: v1.x
      - run: |
          deno --version
          deno run https://deno.land/std/examples/welcome.ts
